export {default as Navbar} from './Navbar/Navbar'
export {default as Products } from './Products/Products'
export {default as Cart } from './Cart/Cart'
export {default as Checkout} from './CheckoutForm/Checkout/Checkout'
export {default as Details} from './Details/Details'
export {default as Categories} from '../components/Categories/Categories'
export {default as Carousel} from './Carousel/Carousel'